### ISSUE TITLE
Does this work with a G6 Play?

### ISSUE THREAD

**Issue by ghost** [RealJohnGalt/g6-gcam-mods#2]
Heya! I was wondering if the magisk modules and the APK work for the Moto G6 Play, since it's the only GCam I could find for this version of the G6. Thanks!

**Comment by zqidev** [comment]
No, you cannot. This is a port for the G6 only (ali), not for the G6 play (jeter).

**Comment by ghost** [comment]
Well, that sucks. Thanks for replying
